SanayeeIdentity_5/Controllers/MainWorkerController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SanayeeIdentity_5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using SanayeeIdentity_5.Data;
using System.Data.Entity;
using SanayeeIdentity_5;

namespace SanayeeIdentity4.Controllers
{
    [Authorize(Roles = "Worker")]

    public class MainWorkerController : Controller
    {
        // GET: MainWorker
        
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        Entities db = new Entities();
        ApplicationDbContext db2 = new ApplicationDbContext();

        public MainWorkerController()
        {
        }

        public MainWorkerController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        [AllowAnonymous]
        public ActionResult WorkerRegister()
        {
            ViewBag.Citys = new SelectList(db.Citys.ToList(), "CityId", "Name");
            ViewBag.Areas = new SelectList(db.Areas.Where(r => r.CityId ==0), "AreaId", "Name");
            ViewBag.Types= new SelectList(db.Types.ToList(), "TypeId", "Name");
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public  ActionResult WorkerRegister(WorkerRegisterViewModel model, HttpPostedFileBase image1)
        {
            ViewBag.Citys = new SelectList(db.Citys.ToList(), "CityId", "Name");
            ViewBag.Areas = new SelectList(db.Areas.Where(r => r.CityId == 0), "AreaId", "Name");
            ViewBag.Types = new SelectList(db.Types.ToList(), "TypeId", "Name");
            if (ModelState.IsValid)
            {
                ApplicationUser User = db2.Users.Where(u => u.PhoneNumber == model.PhoneNumber).FirstOrDefault();
                string Uid = null;
                if (User == null)
                {

                    AdressDetail adress = new AdressDetail() { AreaId = model.AreaId };
                    db.AdressDetails.Add(adress);
                    db.SaveChanges();

                    var user = new ApplicationUser() {Name=model.Name, AddressId = adress.AdressId, UserName = model.Email, Email = model.Email, PhoneNumber = model.PhoneNumber };
                    var result = UserManager.Create(user, model.Password);
                    if (result.Succeeded)
                    {

                    //    SignInManager.SignIn(user, isPersistent: false, rememberBrowser: false);

                        Uid = db2.Users.Where(u => u.PhoneNumber == model.PhoneNumber).First().Id;

                    }
                    else
                    {
                        ViewBag.Citys = new SelectList(db.Citys, "CityId", "Name", model.CityId);
                        ViewBag.Areas = new SelectList(db.Areas.Where(r => r.CityId == model.CityId), "AreaId", "Name", model.AreaId);

                        AddErrors(result);
                        return View(model);
                    }


                }

                else
                {
                    Uid = User.Id;

                }

                UserManager.AddToRoles(Uid, "Worker");

                Worker w = new Worker() {TypeId=model.typeid, Available = false, Onwork = false, SBIN = model.ISBN, UserID = Uid };
                if (image1 != null)
                {                   
                    w.PhotoBin = new byte[image1.ContentLength];
                    image1.InputStream.Read(w.PhotoBin, 0, image1.ContentLength);
                }
                db.Workers.Add(w);
                db.SaveChanges();
                return  RedirectToAction("Login", "Account");





            }
       ViewBag.Citys = new SelectList(db.Citys, "CityId", "Name",model.CityId);
       ViewBag.Areas = new SelectList(db.Areas.Where(r=>r.CityId==model.CityId), "AreaId", "Name",model.AreaId);

            return View(model);
        }


        public ActionResult Index()
        {



            return View();

        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        [AllowAnonymous]

        public JsonResult GetAreaList(string CityId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            int x = int.Parse(CityId);
            List<Area> Arealist = db.Areas.Where(p => p.CityId ==x) .ToList();

            return Json(Arealist, JsonRequestBehavior.AllowGet);
        }


 


        public ActionResult WorkerSceduasls(string UserId)
        {



            Worker worker = db.Workers.Where(w => w.UserID == UserId).FirstOrDefault();
            List<Schedual> List = new List<Schedual>();
            List = db.Scheduals.Where(s => s.WorkerId == worker.WorkerId) .ToList();
            
            return View(List);
        }
        [AllowAnonymous]
        public JsonResult GetReqInlastTwoMin()
        {
            int x = 0;
            try
            {
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                int wid = db.Workers.Where(w => w.UserID == user.Id).FirstOrDefault().WorkerId;
                int s = (db.Scheduals.Where(ss=>ss.WorkerId == wid)).Select(ss => ss.ScedualId).Max();


                x = db.Requests.Where(r => r.ScedualId == s && r.RequestDateTime.Day == DateTime.Now.Day && r.Done == false).Count();

            }
            catch (Exception e)
            {
                x = 0;
    return Json("To Day Reqests: "+ x.ToString(), JsonRequestBehavior.AllowGet);

            }
            return Json("To Day Reqests: " + x.ToString(), JsonRequestBehavior.AllowGet);


        }
        public ActionResult scedialRequsts(string ScedualId)
        {
            int x = 0;
            x = int.Parse(ScedualId);

            Schedual scedual = db.Scheduals.Find(x);
            List<Request> List = new List<Request>();
            List = db.Requests.Where(r => r.ScedualId == x).ToList();

            return View(List);
        }
       
        public PartialViewResult RequstFinish(string RequestId)
        {
            int x = 0;
            x = int.Parse(RequestId);

            Request req = db.Requests.Where(r => r.RequestId == x).FirstOrDefault();

            req.Done = true;

            db.Entry(req).State = EntityState.Modified;
            db.SaveChanges();

            return PartialView("RequestPartial",req);
        }
        [HttpGet]
        public ActionResult WorkerProfile(string UserId)
        {
            
            ApplicationUser user=    db2.Users.Find(UserId);
            AdressDetail address = db.AdressDetails.Find(user.AddressId);
            Worker worker = db.Workers.Where(w => w.UserID == user.Id).First();
            WorkerRegisterViewModel model = new WorkerRegisterViewModel()
            {
                Name = user.Name
                ,
                Email = user.Email
                ,
                AreaId = address.Area.AreaId
                ,
                CityId = address.Area.CityId
               ,
                PhoneNumber = user.PhoneNumber
               ,
                userid = UserId
               ,
                ISBN = worker.SBIN
               ,
                Password = user.PasswordHash
                ,
                ConfirmPassword = user.PasswordHash
                ,
                IsAvailable = (bool)worker.Available
                ,
                PhotoBin = worker.PhotoBin
                , typeid = (int)worker.TypeId


            };
            ViewBag.Citys = new SelectList(db.Citys, "CityId", "Name",model.CityId);
            ViewBag.Areas = new SelectList(db.Areas .Where(ar=>ar.CityId==model.CityId).ToList(), "AreaId", "Name", model.AreaId);
          

            return View(model);
            

          
           
        }
        [HttpPost]
        public ActionResult WorkerProfile(WorkerRegisterViewModel model, HttpPostedFileBase image1)
        {
          
                ApplicationUser user = db2.Users.Find(model.userid);
                List<ApplicationUser> list = new List<ApplicationUser>();
                list = db2.Users.ToList();
            if ((list.Where(u => u.Email == model.Email&&u.Id!=model.userid).Count() < 1||user.Email==model.Email )&& model.Email != null)
            {
                user.Name = model.Name;
                user.Email = model.Email;
                user.UserName = model.Email;
                                if (((list.Where(u => u.PhoneNumber == model.PhoneNumber&&u.Id!=model.userid).Count() < 1 ||model.PhoneNumber==user.PhoneNumber)&&model.PhoneNumber!=null)&&model.AreaId!=0)
                    {
                        user.PhoneNumber = model.PhoneNumber;
                        AdressDetail add = db.AdressDetails.Find(user.AddressId);
                        add.AreaId = model.AreaId;
                        db.Entry(add).State = EntityState.Modified;

SanayeeIdentity_5/Views/MainWorker/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

SanayeeIdentity_5/Views/MainWorker/RequestPartial.cshtml
@model SanayeeIdentity_5.Data.Request
@using SanayeeIdentity_5.Models
<div >
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        @{ ApplicationUser user = new ApplicationDbContext().Users.Find(Model.Userid); }


        <dt>
            Client
        </dt>

        <dd>
            @user.Name
        </dd>
        <dt>
            Client Email
        </dt>

        <dd>
            @user.Email
        </dd>

        <dt>
            Client Phone
        </dt>

        <dd>
            @user.PhoneNumber
        </dd>

        <dt>
           Request Date
        </dt>

        <dd>
            @Model.RequestDateTime
        </dd>

        <dt>
            Area Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressDetail.Area.Name)
        </dd>

        <dt>
            Addres Details
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressDetail.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Schedual.PaidRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Schedual.PaidRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)

        </dt>

        <dd>
            @{@((Model.Done == true ? "تم" : "لم يتم").ToString());}

            @*@Html.ActionLink("تم أنهائة", "RequstFinish", new { Requestid = Model.RequestId })*@
            <br />
            @using (Ajax.BeginForm("RequstFinish", "MainWorker", new AjaxOptions()
            {
                UpdateTargetId = "UpdatePanel" + Model.RequestId.ToString(),
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "loadingpic",
                OnBegin = "HideData",
                OnComplete = "ShowData"

            }))
            {

                @Html.Hidden("RequestId", Model.RequestId)

                <input type="submit" name="btn2" value="انهاء" id="btn2" class="btn btn-success " />
            }


        </dd>
    </dl>
       

   
</div>

SanayeeIdentity_5/Views/MainWorker/WorkerProfile.cshtml
@model  SanayeeIdentity_5.Models.WorkerRegisterViewModel
@using SanayeeIdentity_5.Data;
@{
    ViewBag.Title = "WorkerProfile";
}


<h2>WorkerProfile</h2>

@using (Html.BeginForm("WorkerProfile", "MainWorker", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })

    @Html.Hidden("Email", Model.Email)
    @Html.Hidden("Password", Model.Password)
    @Html.Hidden("ConfirmPassword", Model.ConfirmPassword)
    @Html.Hidden("ISBN", Model.ISBN)
    @Html.Hidden("userid", Model.userid)
    @Html.Hidden("TypeId", Model.typeid)

    <div class="form-group">
        @Html.Label("Photo", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @*@Html.EditorFor(m => m.Name, new { @class = "form-control" })*@
            @{
                var imgsrc = string.Empty;
                if (Model.PhotoBin != null)
                {
                    var base64 = Convert.ToBase64String(Model.PhotoBin);
                    imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                }
                else
                {

                    imgsrc = "/Images/pT78y5n8c.jpg";
                }

            }

            <img src="@imgsrc" width="100" height="100" id="DbImg" />

                <br/><br />
            <input type="file" value="Edit Images" name="image1" class="form-control" id="image1" />
            <img id="ShowImage" />
            <p id="Error"></p>
        </div>

    </div>
    @*<div class="form-group">*@
    @*<div class="col-md-10">
        <input type="file" value="Edit Images" name="image1" class="form-control" id="image1" />
        <img id="ShowImage" />
        <p id="Error"></p>
        @*</div>*@

    @*</div>*@

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @*<h6>Work</h6>*@
        @Html.Label("Worker", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @{ string Type = new Entities().Types.Where(t => t.TypeId == Model.typeid).First().Name;}
            @Type
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.PhoneNumber, new { @class = "form-control" })
        </div>
    </div>


    <h6>---------------------------------------------------------------------------------------------------------------------</h6>
    <div class="form-group">
        @Html.LabelFor(model => model.CityId, "CityID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (ViewBag.Citys != null)
            {
                @*@Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.CityId, ViewBag.Citys as SelectList, "--- Select City ---", new { @class = "form-control" });
            }
            else
            {
                <h2> Plz Insert Catgories</h2>
            }
            @Html.ValidationMessageFor(model => model.CityId, " ", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AreaId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.AreaId, ViewBag.Areas as SelectList, " -- Select Area -- ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AreaId, "", new { @class = "text-danger" })
        </div>
    </div>
    <h6>---------------------------------------------------------------------------------------------------------------------</h6>

    <div class="form-group">
        Is Available ?
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.IsAvailable, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Save" />
        </div>
    </div>



}


@section Scripts {

    <script>
        $(document).ready(function () {

            $("#CityId").change(function () {
                $.get("/MainWorker/GetAreaList", { CityId: $("#CityId").val() }, function (data) {
                    $("#AreaId").empty();

                    $.each(data, function (index, row) {
                        $("#AreaId").append("<option value='" + row.AreaId + "'>" + row.Name + "</option>")

                    });
                });
            });





        });

    </script>
    <script>
        $(document).ready(function () {

            $("#CityId").change(function () {
                $.get("/MainWorker/GetAreaList", { CityId: $("#CityId").val() }, function (data) {
                    $("#AreaId").empty();

                    $.each(data, function (index, row) {
                        $("#AreaId").append("<option value='" + row.AreaId + "'>" + row.Name + "</option>")

                    });
                });
            });





        });
    </script>

    <script>
        function showImage(src, target) {
            var fr = new FileReader();
            fr.onload = function () {
                target.src = fr.result; //<img src="H://file1.jpg" />
                document.getElementById('DbImg').style["display"] = "none";
            }
            fr.readAsDataURL(src.files[0]);
        }
        function putImage() {
            if (!document.getElementById("image1").files[0].type.match('image.*')) {
                document.getElementById("ShowImage").style["display"] = "none";
                document.getElementById("Error").innerHTML = "Please Select Image File";
                document.getElementById("image1").value = "";
            }
            else {
                document.getElementById("Error").innerHTML = "";
                var src = document.getElementById("image1");
                var target = document.getElementById("ShowImage");
                target.style["display"] = "block";
                showImage(src, target);
            }
        }
        document.getElementById('image1').addEventListener('change', putImage, false);
    </script>




    @Scripts.Render("~/bundles/jqueryval")
}
@section Styles{
    <style>
        #ShowImage {
            display: none;
            height: 200px;
            border: 1px solid #000;
            margin: 10px 5px 0 0;
            float: left;
        }

        #Error {
            color: red;
        }
    </style>
}

SanayeeIdentity_5/Views/MainWorker/WorkerRegister.cshtml
@model  SanayeeIdentity_5.Models.WorkerRegisterViewModel
@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("WorkerRegister", "MainWorker", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ISBN, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.ISBN, new { @class = "form-control" })
        </div>

    </div>
    <h6>---------------------------------------------------------------------------------------------------------------------</h6>
    @*<h6>Address</h6>*@
    @*@Html.Label("Address", new { @class = "col-md-2 control-label" })*@
    <div class="form-group">
        @*@Html.LabelFor(model => model.CityId, "CityID", htmlAttributes: new { @class = "control-label col-md-2" })*@
        @Html.Label("City", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @if (ViewBag.Citys != null)
            {
                @*@Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.CityId, ViewBag.Citys as SelectList, "--- Select City ---", new { @class = "form-control" });
            }
            else
            {
                <h2> Plz Insert Catgories</h2>
            }
            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AreaId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.AreaId, ViewBag.Areas as SelectList, " -- Select Area -- ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AreaId, "", new { @class = "text-danger" })
        </div>
    </div>
    <h6>---------------------------------------------------------------------------------------------------------------------</h6>

    <div class="form-group">
    @Html.LabelFor(model => model.typeid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.typeid, ViewBag.Types as SelectList, " -- Select Type -- ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.typeid, "", new { @class = "text-danger" })
        </div>
    </div>
    <h6>---------------------------------------------------------------------------------------------------------------------</h6>

    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Photo", new { @class = "col-md-2 control-label" })
        @*@Html.LabelFor(model => model.FilePhoto, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })*@
            <input type="file" name="image1" class="form-control" id="image1" />
            @*@Html.ValidationMessageFor(model => model.FilePhoto, "", new { @class = "text-danger" })*@

            @*add Image To Show image and P For Error *@
            <img id="ShowImage" />
            <p id="Error"></p>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}
@section Styles{
    <style>
        #ShowImage {
            display: none;
            height: 200px;
            border: 1px solid #000;
            margin: 10px 5px 0 0;
            float: left;
        }

        #Error {
            color: red;
        }
    </style>
}

@section Scripts {
    <script>
        function showImage(src, target) {
            var fr = new FileReader();
            fr.onload = function () {
                target.src = fr.result; //<img src="H://file1.jpg" />
            }
            fr.readAsDataURL(src.files[0]);
        }
        function putImage() {
            if (!document.getElementById("image1").files[0].type.match('image.*')) {
                document.getElementById("ShowImage").style["display"] = "none";
                document.getElementById("Error").innerHTML = "Please Select Image File";
                document.getElementById("image1").value = "";
            }
            else {
                document.getElementById("Error").innerHTML = "";
                var src = document.getElementById("image1");
                var target = document.getElementById("ShowImage");
                target.style["display"] = "block";
                showImage(src, target);
            }
        }
        document.getElementById('image1').addEventListener('change', putImage, false);
    </script>

    <script>
        $(document).ready(function () {

            $("#CityId").change(function () {
                $.get("/MainWorker/GetAreaList", { CityId: $("#CityId").val() }, function (data) {
                    $("#AreaId").empty();

                    $.each(data, function (index, row) {
                        $("#AreaId").append("<option value='" + row.AreaId + "'>" + row.Name + "</option>")

                    });
                });
            });





        });
    </script>


    @Scripts.Render("~/bundles/jqueryval")
}

SanayeeIdentity_5/Views/MainWorker/WorkerSceduasls.cshtml
@model IEnumerable<SanayeeIdentity_5.Data.Schedual>

@{
    ViewBag.Title = "WorkerSceduasls";
}

<h2>WorkerSceduasls</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@



@foreach (var item in Model)
{
    
        @Html.Partial("scedialPartial", item);
   
}

SanayeeIdentity_5/Views/MainWorker/scedialPartial.cshtml
@model  SanayeeIdentity_5.Data.Schedual

<div>
    <h4>Schedual</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>


        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaidRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaidRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>



        @*<dt>
            @Html.DisplayNameFor(model => model.Worker.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Worker.UserID)
        </dd>*@

        <dt>
            Requests
        </dt>
        <dd>
            @Html.ActionLink("Requists", "scedialRequsts", new { ScedualId = Model.ScedualId })
        </dd> 
    </dl>
</div>

SanayeeIdentity_5/Views/MainWorker/scedialRequsts.cshtml
@model IEnumerable<SanayeeIdentity_5.Data.Request>

<p>
    @Html.ActionLink("Create New", "Create")
</p>



@foreach (var item in Model)
{
    <div id=@{@("UpdatePanel" + item.RequestId.ToString()); }>

        @Html.Partial("RequestPartial", item)
        @*googel map feto*@
        @{
            <span>@item.AdressDetail.Map.Latitude</span>
            <span>@item.AdressDetail.Map.Longitude</span>
            if (item.AdressDetail.Map.Latitude == 0 || item.AdressDetail.Map.Longitude == 0)
            {
                <iframe id="googel-map" width="300" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                        src="https://maps.google.co.uk?output=embed"></iframe>
            }
            else
            {
                <iframe id="googel-map" width="300" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
                        src='https://maps.google.co.uk?q="@item.AdressDetail.Map.Latitude,@item.AdressDetail.Map.Longitude"&z=40&output=embed'></iframe>
            }
        }
    </div>



            }
<div id="loadingpic" style="display:none">
    <img id="loading" alt="Loading Image" src="~/Content/Images/1.gif" />
</div>



@section Scripts{


<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>

        function HideData() {
            document.getElementById("UpdatePanel").style.display ="none" ;

        }
        function ShowData() {
            document.getElementById("UpdatePanel").style.display = "block";

        }
    </script>
}
@section Styles{
    <style>
        td {
            vertical-align: middle;
        }

        .ProductImage {
            height: 50px;
            border: 1px solid #000;
            -moz-border-radius: 10px;
            -webkit-border-radius: 10px;
            border-radius: 10px;
        }
    </style>
}