SanayeeIdentity_5/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SanayeeIdentity_5.Data;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;
using SanayeeIdentity_5.Controllers;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity.Infrastructure;
using SanayeeIdentity_5.Models;
using SanayeeIdentity_5;

namespace SanayeeIdentity_5.Controllers
{
    [Authorize(Roles = "Client")]

    public class RequestsController : Controller
    {
        //حل مشكلة الركويس خلى الركويس كى هوا البريمى كى وهتلاقى السبب تحت



        private ApplicationDbContext dbc = new ApplicationDbContext();
        private Entities db = new Entities();

        // private Entities dbc = new Entities();
        private ApplicationUserManager _userManager;
        public ActionResult SearchWorkerByUsers(string SearchKey)
        {
            if (SearchKey != "")
            {
                int MaxRate = int.Parse(db.Workers.Max(e => e.TotalRate).ToString());
                //i have to make two diffrent quires cuz the data belong to diffrent  edml file or dbcontex
                var helpWithUserList = dbc.Users.ToList();
                var ws = helpWithUserList.Join(db.Workers, user => user.Id, worker => worker.UserID, (user, worker) => new WorkerViewCardModelcs
                {

                    MaxRateofWorkers = MaxRate,
                    Name = user.Name,
                    WorkerId = worker.WorkerId,
                    AddressId = user.AddressId,
                    UserName = user.UserName,
                    SBIN = worker.SBIN,
                    PhoneNumber = user.PhoneNumber,
                    PhotoBin = worker.PhotoBin,
                    TotalRate = worker.TotalRate,
                    Email = user.Email,
                    //extra to remove buttoms
                    Available = worker.Available,
                    Onwork = worker.Onwork,
                    TypeName = db.Workers.Join(db.Types, w => w.TypeId, t => t.TypeId, (w, t) => t).First().Name.ToString()
                }
                        //here the update
                        ).ToList().Where(e=>e.Name.Contains(SearchKey)).ToList();
                        
                      //var s= Workers.Where(worker => worker.Name.Contains(SearchKey)).ToList();
                return PartialView("_WorkerCard", ws);
            }
            else return View();
        }

        public ActionResult InsertComplain(string WorkerId, string head, string body)
        {
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());


            if (WorkerId != "" && body != "")
            {
                Complaint cmp = new Complaint();
                cmp.datetime = DateTime.Now;
                cmp.Workerid = WorkerId;
                cmp.MessageHead = head;
                cmp.Text = body;
                cmp.Userid = user.Id;

                db.Complaints.Add(cmp);
                db.SaveChanges();
                return Json(new { message = $"Your Compline Is Done at" }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { message = $"Your compline Isn't Done " }, JsonRequestBehavior.AllowGet);



        }
        public ActionResult InsertingRateofWorker(string workerid, string rate)
        {

            int wi = int.Parse(workerid);
            db.Workers.Where(e => e.WorkerId == wi).SingleOrDefault().TotalRate += int.Parse(rate);
            db.SaveChanges();
            return null;
        }
        public JsonResult GetAreas(string City)
        {
            try
            {
                db.Configuration.ProxyCreationEnabled = false;
                int cityid = Convert.ToInt32(City);
                var Areas = db.Areas.Where(e => e.CityId == cityid).ToList();
                //ViewBag.AreasID = new SelectList(db.Areas, "Areaid", "Name");
                return Json(Areas, JsonRequestBehavior.AllowGet);
            }
            catch (FormatException)
            {
                this.Dispose();
                return null;
            }
        }
        public ActionResult GetWorkerByCityAreaType(string City, string Area, string Type)
        {
            if (City != "" && Area != "" && Type != "")
            {
                try
                {


                    db.Configuration.ProxyCreationEnabled = false;
                    //الشروط اتلاته متاح بيشتغل بى الفعل و اخر اسكدول ليه  لسه مفتوح المده
                    var datenow = DateTime.Now;
                    var Workers = db.Scheduals.Where(e => e.EndDate > datenow && e.Worker.Onwork == true && e.Worker.Available == true)
                        .Select(z => z.Worker).Distinct().ToList();
                    //this will return html you need to bind this to your model  when accepted as response
                    int cityid = int.Parse(City);
                    int areaid = int.Parse(Area);
                    int typeint = int.Parse(Type);
                    var WorkersThatHasUser = Workers.Join(dbc.Users, e => e.UserID, u => u.Id, (e, u) => new { e, u.AddressId }).ToList();
                    //City Area type here search
                    var moreeasy = WorkersThatHasUser.Join(db.AdressDetails, z => z.AddressId, p => p.AdressId, (e, u) => new { e.e, u.AreaId }).Join(db.Areas, u => u.AreaId, e => e.AreaId, (y, u) => new { y.e, u })
                       .Where(z => z.u.CityId == cityid && z.u.AreaId == areaid && z.e.TypeId == typeint).Select(z => z.e).ToList();
                    // Note that Annonmous object will cauze runtime problem cuz it just local you must made a modelclass

                    var SchedualOfWorkers = moreeasy.Join(db.Scheduals, e => e.WorkerId, s => s.WorkerId, (e, s) => s).ToList();
                    int MaxRate = int.Parse(db.Workers.Max(e => e.TotalRate).ToString());

                    var WorkerFullinfo = moreeasy.Join(dbc.Users, e => e.UserID, i => i.Id, (e, i) => new WorkerViewCardModelcs
                    {
                        MaxRateofWorkers = MaxRate,
                        Name = i.Name,
                        WorkerId = e.WorkerId,
                        AddressId = i.AddressId,
                        UserName = i.UserName,
                        SBIN = e.SBIN,
                        PhoneNumber = i.PhoneNumber,
                        PhotoBin = e.PhotoBin,
                        TotalRate = e.TotalRate,
                        Email = i.Email,
                        ScedualId = SchedualOfWorkers.Where(w => w.WorkerId == e.WorkerId).ToList().Last().ScedualId,
                        //TypeName = moreeasy.Join(db.Types, w => w.TypeId, t => t.TypeId, (w, t) => t).First().Name.ToString()
                        TypeName = db.Types.Where(z => z.TypeId == e.TypeId).SingleOrDefault().Name
                    }

                     ).ToList();

                    ViewBag.All =WorkerFullinfo;
                    //Make sure that you have not error in syntax in the view cuz it will not render
                    return PartialView("_WorkerCard", WorkerFullinfo);
                }
                catch (FormatException)
                {
                    this.Dispose();
                    return null;
                }
            }
            else /*if(City == "" || Area == "")*/
            {
                if (Type == null || Type == "")
                {
                    return PartialView("_WorkerCard", "");
                }
                else
                {
                    //search egypt by type
                    db.Configuration.ProxyCreationEnabled = false;
                    //الشروط اتلاته متاح بيشتغل بى الفعل و اخر اسكدول ليه  لسه مفتوح المده
                    var datenow = DateTime.Now;
                    var Workers = db.Scheduals.Where(e => e.EndDate > datenow && e.Worker.Onwork == true && e.Worker.Available == true)
                        .Select(z => z.Worker).Distinct().ToList();
                    //this will return html you need to bind this to your model  when accepted as response

                    int typeint = int.Parse(Type);

                    var WorkersThatHasUser = Workers.Join(dbc.Users, e => e.UserID, u => u.Id, (e, u) => new { e, u.AddressId }).ToList();
                    //here the type only
                    var moreeasy = WorkersThatHasUser.Join(db.AdressDetails, z => z.AddressId, p => p.AdressId, (e, u) => new { e.e, u.AreaId }).Join(db.Areas, u => u.AreaId, e => e.AreaId, (y, u) => new { y.e, u })
                       .Where(z => z.e.TypeId == typeint).Select(z => z.e).ToList();
                    // Note that Annonmous object will cauze runtime problem cuz it just local you must made a modelclass

                    var SchedualOfWorkers = moreeasy.Join(db.Scheduals, e => e.WorkerId, s => s.WorkerId, (e, s) => s).ToList();

                    int MaxRate = int.Parse(db.Workers.Max(e => e.TotalRate).ToString());
                    var WorkerFullinfo = moreeasy.Join(dbc.Users, e => e.UserID, i => i.Id, (e, i) => new WorkerViewCardModelcs
                    {
                        MaxRateofWorkers = MaxRate,
                        Name = i.Name,
                        WorkerId = e.WorkerId,
                        AddressId = i.AddressId,
                        UserName = i.UserName,
                        SBIN = e.SBIN,
                        PhoneNumber = i.PhoneNumber,
                        PhotoBin = e.PhotoBin,
                        TotalRate = e.TotalRate,
                        Email = i.Email,
                        ScedualId = SchedualOfWorkers.Where(w => w.WorkerId == e.WorkerId).ToList().Last().ScedualId,

SanayeeIdentity_5/Views/Requests/Create.cshtml
@model SanayeeIdentity_5.Data.Request

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Userid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Userid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Userid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ScedualId, "ScedualId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ScedualId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ScedualId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Done, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Done)
                    @Html.ValidationMessageFor(model => model.Done, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressId, "AddressId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AddressId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AddressId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SanayeeIdentity_5/Views/Requests/Delete.cshtml
@model SanayeeIdentity_5.Data.Request

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Done)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressDetail.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressDetail.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Schedual.PaidRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Schedual.PaidRate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SanayeeIdentity_5/Views/Requests/Details.cshtml
@model SanayeeIdentity_5.Data.Request

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Done)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdressDetail.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdressDetail.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Schedual.PaidRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Schedual.PaidRate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SanayeeIdentity_5/Views/Requests/Edit.cshtml
@model SanayeeIdentity_5.Data.Request

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestId, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Userid)

        @Html.HiddenFor(model => model.ScedualId)

        @Html.HiddenFor(model => model.RequestDateTime)

        <div class="form-group">
            @Html.LabelFor(model => model.Done, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Done)
                    @Html.ValidationMessageFor(model => model.Done, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressId, "AddressId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AddressId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AddressId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SanayeeIdentity_5/Views/Requests/Index.cshtml
@model IEnumerable<SanayeeIdentity_5.Data.Request>

@{
    ViewBag.Title = "Sany3e";
    //Layout = "~/Views/Shared/_Layout.cshtml";
   // Layout = "~/Views/Shared/_Feto.cshtml";
}

@*<div style="display:inline-block">
    @using (Html.BeginForm("SearchWorkerByUsers", "Requests", FormMethod.Post))
    {
        <div>
            <fieldset>
                <legend> Search Full </legend>
                <div> @Html.Label("SearchKey")</div> <div> @Html.TextBox("SearchKey", null, htmlAttributes: new { @class = "form-control" }) </div>
                <input type="submit" name="btnsubmit" value="Search" class="btn btn-default " />
            </fieldset>
        </div>
    }
</div>*@
<div style="display:inline-block ;">
    @using (Ajax.BeginForm("SearchWorkerByUsers", new AjaxOptions()
    {
        UpdateTargetId = "WorkersDiv",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "loadingpic",
        OnBegin = "HideData",
        OnComplete = "ShowData"
    }))
    {
        <div>
            <fieldset>
                <legend> Search Names </legend>
                <label for="SearchKey"> Enter Name : </label>
                @Html.TextBox("SearchKey", null, new { @class = "form-control", required = "required", placeholder = "اسم عامل هنا" })
                <br />
                <input type="submit" name="btn2" value="Search Ajax" id="btn2" class="btn btn-success " />
            </fieldset>
        </div>
    }

</div>


<div class="form-inline center">
    <h1>Requests Service</h1>
    @if (ViewBag.CityID != null)
    {
        <div class="form-group">
            <div><label for="City">City</label></div>
            <div>@Html.DropDownList("City", ViewBag.CityID as SelectList, "--Select City--", new { @class = "City form-control" })</div>
        </div>
    }

    <div class="form-group">
        <div><label for="Areas">Area</label></div>
        <div>@Html.DropDownList("Areas", new SelectList(""), "--Select Area--", new { @class = "Areas form-control", @Required = true })</div>
    </div>
    <div class="form-group">
        <div><label for="Type">Type</label></div>
        <div>@Html.DropDownList("Type", ViewBag.TypeID as SelectList, "--Worker Type--", new { @class = "Worker form-control", @Required = true })</div>
    </div>
    <div class="form-group">
        <div><label for="Address">Detailed Address</label></div>
        <div>@Html.TextArea("Address", null, 3, 8, new { @class = "Address form-control", @placeholder = "Enter Detailed Address" })</div>
        <span id="OrderError"></span>
    </div>

</div>


<div id="loadingpic" style="display:none">
    <img id="loading" alt="Loading Image" src="~/Content/Images/icons/toggle-icon-1.png" />
</div>

<div class="containerr" id="WorkersDiv">


</div>


<input type="hidden" id="CityName" value="" />
@section styless{
    <link href="~/Content/FetoStyle.css" rel="stylesheet" />


}
@section scripts{
    @*download the nugets*@
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        function HideData() {
            document.getElementById("WorkersDiv").style.display = "none";

        }
        function ShowData() {
            document.getElementById("WorkersDiv").style.display = "block";

        }
    </script>


    <script>

        $("#Type").change(function () {

            $.ajax({

                type: 'get',
                url: "/Requests/GetWorkerByCityAreaType",
                data: { City: $("#City").val(), Area: $("#Areas").val(), Type: $("#Type").val() },
                contentType: 'application/json; charset=utf-8',
                success: function (response) {
                    //we gonna load the partial view inside the Worker Div
                    $("#WorkersDiv").html(response);
                    $("#OrderError").text("");


                },
                error: function () {
                    $("#OrderError").text("Don't Select  --Worker Type-- Idiot i will hack your device ");
                    $("#OrderError").addClass("text text-danger");
                    $("#WorkersDiv").html();
                }
            });
        });

        $("#Areas").change(function () {

            $.ajax({

                type: 'get',
                url: "/Requests/GetWorkersByCityAndArea",
                data: { City: $("#City").val(), Area: $("#Areas").val(), Type: $("#Type").val() },
                contentType: 'application/json; charset=utf-8',
                success: function (response) {
                    //we gonna load the partial view inside the Worker Div
                    $("#WorkersDiv").html(response);


                },
                error: function () {
                    $("#OrderError").text("It Seem That Your Area Hasn't Workers Please Select option select-city then Your City");
                    $("#WorkersDiv").html();
                }
            });
        });
    </script>
    <script>


        //the RequestDate to make it Datepicker

        //when The Page first Load
        $(document).ready(function () {

            //var lat, long;
            ////geting the lngituide and mangitude here  directly
            //fetofuntion = function (pos) {

            //     lat = pos.coords.latitude,
            //        long = pos.coords.longitude,
            //        //contine lat+long
            //        coords = lat + ','+ long;

            //}


            ////the callback funtion to use the data in variables and use it later feto.
            //navigator.geolocation.getCurrentPosition(fetofuntion);


            $("#City option").click(function () {
                console.log('click');
            });


            //get Workers by
            $("#City").change(function () {
                //continue from here take this lat and long and store it in the database
                //alert("2 "+lat + "  " + long);
                $.ajax({

                    type: 'get',
                    url: "/Requests/GetWorkersByCity",
                    data: { City: $("#City option:selected").val(), Type: $("#Type").val() },
                    contentType: 'application/json; charset=utf-8',
                    success: function (response) {
                        //we gonna load the partial view inside the Worker Div
                        $("#WorkersDiv").html(response);


                    },
                    error: function () {
                        $("#OrderError").text("If Your Area has No workers Select (Select-City) then Your City");
                        $("#WorkersDiv").html().empty();
                    }
                });


                $("#Areas").empty();
                $.get("/Requests/GetAreas", { City: $("#City").val() }, function (data) {
                    var s = "<option value=''> --SelectArea-- </option>"
                    $.each(data, function (index, row) {


                        s += "<option value='" + row.AreaId + "'>" + row.Name + "</option>";

                    });
                    $("#Areas").html(s);

                });
                // Geting the Worker from first select of the city


            })









        });



    </script>






}

SanayeeIdentity_5/Views/Requests/_GetWorkersByCity.cshtml
@model IEnumerable<SanayeeIdentity_5.Models.WorkerViewCardModelcs>
@*<span>@item.SBIN</span>
    <span>@item.WorkerId</span>
    <span>@item.UserName</span>*@
<span>hello </span>
<section class="section-container bord">
    <section class="meet-the-team">

        <h1 class="border-line-center text-center">Workers</h1>
        <div class="center">
            <div class="clearfix row">
                @foreach (var item in Model)
                {


                    @*here foreach*@
                    <!-- Member 1 -->
                    <section class="meet-the-team">
                        <article class="member col-lg-4 col-md-4 col-sm-5 col-xs-12">
                            <figure><img src="~/Content/images/resource/team-1.jpg " alt="image not supported yet" /><a class="overlay"></a></figure>
                            <div class="member-info">
                                <h4>Dr. Jack Johnson</h4>
                                <h5><a href="#">Rehabilitation Therapy</a></h5>
                                <progress>here is the rate</progress>
                                <h4 class="city">@item.SBIN</h4>
                                <h4>@item.WorkerId</h4>
                            </div>

                            <ul class="social clearfix anim-3-all">
                                <li class="hvr-ripple-out"><a href="#"><span class="flaticon-facebook31"></span></a></li>
                                <li class="hvr-ripple-out"><a href="#"><span class="flaticon-twitter1"></span></a></li>
                                <li class="hvr-ripple-out"><a href="#"><span class="flaticon-google116"></span></a></li>
                                <li class="hvr-ripple-out"><a href="#"><span class="flaticon-instagram12"></span></a></li>
                            </ul>
                        </article>
                    </section>


                }
            </div>
        </div>
    </section>
</section>